spring:
  profiles.active: test

spring.datasource:
  driver-class-name: org.mariadb.jdbc.Driver
  dbcp2:
    test-on-borrow: true
    validation-query: SELECT 1

spring.main.allow-bean-definition-overriding: true

---
spring:
  profiles: test

spring.datasource:
  url: jdbc:mariadb://192.168.1.211:3306/make3dModels
  username: kirill
  password:

spring.jpa:
  show-sql: true

server:
  port: 8899


---
spring:
  profiles: work

